### ISSUE TITLE
sdk-path wrong

### ISSUE THREAD

**Issue by xstable** [rhdeck/react-native-update-gradle#1]
Here create an SDK-Path:

https://github.com/rhdeck/react-native-update-gradle/blob/02582627b1dce12d24f69f1ce026c62b0906ac1c/index.js#L11

But this requires that all users has the same path like you. For me I have `/home/me/Android/Sdk`, and this fully break your implementation, because SDK.dir is set wrong.

Better check first if $ANDROID_HOME is set, and if not scan $HOME and figure out the right path of the SDK for the given installation.

Maybe do it like this: 
```JS
  return (process.env["ANDROID_HOME"]!==undefined) ? process.env["ANDROID_HOME"] : Path.join(process.env["HOME"], "Library", "Android", "sdk");

```

**Comment by rhdeck** [comment]
Good point. Updated and published as 1.0.1
